#!/usr/bin/bash

# Program:      dmenu-dev
# Author:       Michael Nogueira
# Date Created: 2023/10/23
# Last Updated: 2023/10/23
#
# **this script depends on dmenu**
#
# Opens a folder or file in neovim
# select "." to open current folder, or select a file

DIR="$HOME/Dev"

while [ -z "$CHOICE" ]; do
  DIR_CONTENTS=("$DIR"/*)
  CHOICES=(".." "." "${DIR_CONTENTS[@]}")
  CHOICE=$(printf '%s\n' "${CHOICES[@]}" | dmenu -i -l 10 -p "Open in nvim:")
  [[ -z "$CHOICE" ]] && exit

  # escape spaces
  SAFE_DIR=$(echo "$DIR" | sed 's! !\\ !g')
  [[ "$CHOICE" == "." ]] && setsid kitty -d $SAFE_DIR -- nvim && exit

  NAME=$(echo "$CHOICE" | awk -F / '{print $NF}')
  SAFE_NAME=$(echo "$NAME" | sed 's! !\\ !g')

  if [[ -f "$CHOICE" ]]; then
    setsid kitty -d $SAFE_DIR -- nvim $SAFE_NAME && exit
  fi

  if [[ "$CHOICE" == ".." ]]; then
    CHILD=$(echo "$DIR" | awk -F / '{print $NF}')
    DIR="${DIR/"/$CHILD"/}"
  else
    DIR="$CHOICE"
  fi

  CHOICE=""
done


