#!/usr/bin/bash

# Program:      dmenu-dev
# Author:       Michael Nogueira
# Date Created: 2023/10/23
# Last Updated: 2023/10/23
#
# **this script depends on dmenu**
#
# Opens a folder or file in neovim
# select "." to open current folder, or select a file

DIR="$HOME/Dev"

while [ -z "$CHOICE" ]; do
  echo $DIR
  DIR_CONTENTS=("$DIR"/*)
  CHOICES=(".." "." "${DIR_CONTENTS[@]}")
  CHOICE=$(printf '%s\n' "${CHOICES[@]}" | dmenu -i -l 10 -p "Open in nvim:")
  [[ -z "$CHOICE" ]] && exit

  SAFE_DIR=$(echo "$DIR" | sed 's! !\\ !g')
  [[ "$CHOICE" == "." ]] && setsid gnome-terminal -- sh -c "cd $SAFE_DIR && nvim" && exit

  NAME=$(echo "$CHOICE" | awk -F / '{print $NF}')
  SAFE_NAME=$(echo "$NAME" | sed 's! !\\ !g')
  echo $SAFE_DIR
  echo $SAFE_NAME
  if [[ -f "$CHOICE" ]]; then
    # SAFE_DIR="${CHOICE/"/$SAFE_NAME"/}"
    setsid gnome-terminal -- sh -c "cd $SAFE_DIR && nvim $SAFE_NAME" && exit
  fi

  if [[ "$CHOICE" == ".." ]]; then
    DIR="${DIR/"/$NAME"/}"
  else
    DIR="$CHOICE"
  fi


  CHOICE=""
done


